V4 api
fdelbos/go-teamweek pull request #3
Opened 2018-09-17 08:17 UTC by fdelbos

2018-09-17 09:59 UTC, shedokan requested changes
Some of what I've written are TW bugs, either in the docs or API, for now we can comment those fields out and please recheck them and notify TW to fix those bugs.

2018-09-17 09:59 UTC, shedokan commented on teamweek/teamweek.go
> +		Weight           int64    `json:"weight,omitempty"`
`weight` is returned as a float, `"weight":0.0`:
```
panic: json: cannot unmarshal number 0.0 into Go struct field Task.weight of type int64
```

2018-09-17 09:59 UTC, shedokan commented on teamweek/teamweek.go
> +		Color            string   `json:"color,omitempty"`
Color is returned as an integer `"color_id":29,"color":29`:
```
panic: json: cannot unmarshal number into Go struct field Task.color of type string
```

2018-09-17 09:59 UTC, shedokan commented on teamweek/teamweek.go
> +		ColorID   string `json:"color_id,omitempty"`
Should be `int64`

2018-09-17 09:59 UTC, shedokan commented on teamweek/teamweek.go
> +		Color     string `json:"color,omitempty"`
Color is returned as an integer `"color_id":29,"color":29`:
```
panic: json: cannot unmarshal number into Go struct field Project.color of type string
```

2018-09-17 09:59 UTC, shedokan commented on teamweek/teamweek.go
> +		Color     string `json:"color,omitempty"`
Color is returned as an integer `"color_id":29,"color":29`:
```
panic: json: cannot unmarshal number into Go struct field Milestone.color of type string
```

2018-09-17 09:59 UTC, shedokan commented on teamweek/teamweek.go
> +		Color             string `json:"color,omitempty"`
`color` is not returned for members

2018-09-17 09:59 UTC, shedokan commented on teamweek/teamweek.go
> +		ProjectIDs []int64     `json:"project_ids,omitempty`
Missing `"` at the end

2018-09-17 09:59 UTC, shedokan commented on teamweek/client.go
> +func (c *Client) request(urlStr, method string, dest, body interface{}) error {
Nit picking: As `dest` is optional it seems, maybe have it last?

2018-09-17 09:59 UTC, shedokan commented on teamweek/client.go
> +		if resp.StatusCode >= 400 { // for every other error
Why is this last one needs to be inside `default:`?

2018-09-17 09:59 UTC, shedokan commented on teamweek/client.go
> +func (c *Client) post(url string, dest, body interface{}) error {
What's the point of these **private** methods if they are not used within the library?

2018-09-17 10:02 UTC, fdelbos commented
I ll remove the color fields and other ambiguous fields as they are not needed

2018-09-17 10:17 UTC, fdelbos commented on teamweek/client.go
> +func (c *Client) post(url string, dest, body interface{}) error {
I was hoping i could write a real lib but, no time for that...

2018-09-17 10:19 UTC, fdelbos commented on teamweek/client.go
> +func (c *Client) request(urlStr, method string, dest, body interface{}) error {
body is optional for get and delete (i was hoping to do post and put...) but the dest is optionnal only for delete so i think we should keep it like that.

2018-09-17 10:19 UTC, fdelbos commented on teamweek/teamweek.go
> +		ProjectIDs []int64     `json:"project_ids,omitempty`
good catch!

2018-09-17 10:27 UTC, shedokan commented on teamweek/client.go
> +func (c *Client) post(url string, dest, body interface{}) error {
You need a usecase for that, otherwise it'll get stale.

2018-09-17 10:28 UTC, fdelbos commented on teamweek/client.go
> +func (c *Client) post(url string, dest, body interface{}) error {
I ll remove all that and hopefully some day could finish it.

2018-09-20 07:15 UTC, shedokan approved these changes
One refactoring comment wasn't dealt with, but overall LGTM

2018-09-21 06:49 UTC, merged